#include <stdio.h>

int main() {
    int num1, num2, gcd;
    printf("Enter two numbers: ");
    scanf("%d %d", &num1, &num2);

    // Find the GCD using Euclid's algorithm
    while (num2 != 0) {
        int temp = num2;
        num2 = num1 % num2;
        num1 = temp;
    }
    gcd = num1;

    printf("GCD of %d and %d is %d", num1, num2, gcd);
    return 0;
}
/*The code generated by the copilot gives the correct answer but the problem is when it prints the gcd of 2 numbers is; 
instead of printing the initial numbers it gives the numbers as thier reduced form , i.e. the state the numbers reach at the end of 
program*/