l = float(input("Enter the length of the cuboid: "))
b = float(input("Enter the breadth of the cuboid: "))
h = float(input("Enter the height of the cuboid: "))
a = 2 * (l * b + b * h + h * l)
print("The total surface area of the rectangle is: ", a)
